// El surtido del supermercado de prueba: por cada categoría, 25 productos base con su
// precio de referencia en centavos, 5 presentaciones con el factor que multiplica ese
// precio, y marcas inventadas. 25 × 5 da los 125 productos de cada categoría (RF-012).

export type CategoriaDelSurtido = {
  nombre: string;
  // Color de fondo de las fotos generadas.
  color: string;
  frase: string;
  marcas: string[];
  presentaciones: [etiqueta: string, factor: number][];
  bases: [nombre: string, precioCentavos: number][];
};

export const SURTIDO: CategoriaDelSurtido[] = [
  {
    nombre: "Frutas y verduras",
    color: "#2E7D32",
    frase: "Producto fresco, seleccionado a diario.",
    marcas: ["Huerta Viva", "Campo Claro", "Finca El Roble", "Verde Valle"],
    presentaciones: [
      ["250 g", 0.3],
      ["500 g", 0.55],
      ["1 kg", 1],
      ["2 kg", 1.9],
      ["caja de 5 kg", 4.4],
    ],
    bases: [
      ["Limón", 180],
      ["Naranja", 150],
      ["Manzana roja", 320],
      ["Manzana verde", 340],
      ["Plátano", 120],
      ["Piña", 210],
      ["Papaya", 190],
      ["Sandía", 110],
      ["Melón", 170],
      ["Uva verde", 480],
      ["Fresa", 520],
      ["Mango", 260],
      ["Aguacate", 450],
      ["Tomate", 200],
      ["Cebolla blanca", 140],
      ["Cebolla morada", 160],
      ["Papa", 130],
      ["Zanahoria", 125],
      ["Pepino", 135],
      ["Pimiento verde", 280],
      ["Brócoli", 310],
      ["Lechuga", 230],
      ["Espinaca", 350],
      ["Yuca", 115],
      ["Ajo", 620],
    ],
  },
  {
    nombre: "Carnes y pescados",
    color: "#B23A3A",
    frase: "Empacado al vacío y mantenido en cadena de frío.",
    marcas: ["Don Fermín", "Corral Norte", "Mar Abierto", "La Parrilla"],
    presentaciones: [
      ["250 g", 0.28],
      ["500 g", 0.54],
      ["1 kg", 1],
      ["1,5 kg", 1.45],
      ["bandeja familiar de 2 kg", 1.9],
    ],
    bases: [
      ["Pechuga de pollo", 720],
      ["Muslo de pollo", 480],
      ["Alitas de pollo", 560],
      ["Pollo entero", 420],
      ["Carne molida de res", 780],
      ["Lomo de res", 1650],
      ["Costilla de res", 890],
      ["Bistec de res", 1120],
      ["Chuleta de cerdo", 760],
      ["Lomo de cerdo", 940],
      ["Costilla de cerdo", 820],
      ["Tocino", 1280],
      ["Chorizo", 870],
      ["Salchicha de pavo", 690],
      ["Jamón de pierna", 1150],
      ["Pechuga de pavo", 1340],
      ["Filete de tilapia", 980],
      ["Filete de corvina", 1480],
      ["Filete de salmón", 2450],
      ["Atún fresco", 1890],
      ["Camarón", 1750],
      ["Calamar", 1220],
      ["Sardina fresca", 540],
      ["Hígado de res", 410],
      ["Albóndigas de res", 830],
    ],
  },
  {
    nombre: "Lácteos y huevos",
    color: "#3D6FB6",
    frase: "Mantener refrigerado.",
    marcas: ["La Pradera", "Valle Blanco", "Granja Alba", "Doña Lucha"],
    presentaciones: [
      ["individual", 0.3],
      ["mediano", 0.6],
      ["grande", 1],
      ["familiar", 1.8],
      ["paquete de 6", 2.6],
    ],
    bases: [
      ["Leche entera", 135],
      ["Leche descremada", 140],
      ["Leche deslactosada", 165],
      ["Leche de almendra", 310],
      ["Leche evaporada", 150],
      ["Leche condensada", 220],
      ["Yogur natural", 190],
      ["Yogur de fresa", 205],
      ["Yogur griego", 290],
      ["Yogur bebible", 175],
      ["Queso fresco", 430],
      ["Queso mozzarella", 520],
      ["Queso cheddar", 560],
      ["Queso crema", 340],
      ["Queso parmesano", 780],
      ["Queso rallado", 410],
      ["Mantequilla con sal", 360],
      ["Mantequilla sin sal", 365],
      ["Margarina", 240],
      ["Crema de leche", 260],
      ["Crema agria", 255],
      ["Huevos blancos", 280],
      ["Huevos rojos", 300],
      ["Huevos de codorniz", 350],
      ["Requesón", 330],
    ],
  },
  {
    nombre: "Panadería",
    color: "#B5782E",
    frase: "Horneado en el día.",
    marcas: ["Horno Dorado", "La Espiga", "Masa Madre", "Pan del Barrio"],
    presentaciones: [
      ["unidad", 0.25],
      ["paquete de 4", 0.9],
      ["paquete de 6", 1.3],
      ["paquete de 12", 2.4],
      ["bolsa familiar", 3],
    ],
    bases: [
      ["Pan blanco", 190],
      ["Pan integral", 230],
      ["Pan de centeno", 280],
      ["Pan de molde", 260],
      ["Pan de hamburguesa", 240],
      ["Pan de perro caliente", 235],
      ["Pan francés", 150],
      ["Pan de ajo", 290],
      ["Pan dulce", 210],
      ["Pan de yema", 220],
      ["Croissant", 320],
      ["Dona glaseada", 300],
      ["Muffin de vainilla", 340],
      ["Muffin de chocolate", 350],
      ["Galleta de avena", 270],
      ["Galleta de mantequilla", 265],
      ["Tortilla de harina", 215],
      ["Tortilla de maíz", 160],
      ["Pan pita", 245],
      ["Bagel", 330],
      ["Empanada de queso", 310],
      ["Rollo de canela", 360],
      ["Bizcocho de naranja", 420],
      ["Tostadas", 205],
      ["Palitos de pan", 185],
    ],
  },
  {
    nombre: "Despensa",
    color: "#8A6D3B",
    frase: "Conservar en un lugar fresco y seco.",
    marcas: ["Buen Grano", "Alacena", "Sabor Casero", "Del Molino"],
    presentaciones: [
      ["200 g", 0.25],
      ["400 g", 0.45],
      ["1 kg", 1],
      ["2 kg", 1.9],
      ["saco de 5 kg", 4.5],
    ],
    bases: [
      ["Arroz blanco", 210],
      ["Arroz integral", 260],
      ["Frijol negro", 290],
      ["Frijol rojo", 300],
      ["Lenteja", 310],
      ["Garbanzo", 340],
      ["Azúcar blanca", 195],
      ["Azúcar morena", 215],
      ["Sal fina", 90],
      ["Harina de trigo", 180],
      ["Harina de maíz", 170],
      ["Avena en hojuelas", 320],
      ["Espagueti", 240],
      ["Macarrón", 245],
      ["Fideo fino", 235],
      ["Café molido", 980],
      ["Cacao en polvo", 760],
      ["Maíz para palomitas", 280],
      ["Quinua", 890],
      ["Maní tostado", 640],
      ["Pasas", 720],
      ["Granola", 580],
      ["Cereal de maíz", 520],
      ["Pan rallado", 330],
      ["Leche en polvo", 1150],
    ],
  },
  {
    nombre: "Bebidas",
    color: "#1E88A8",
    frase: "Servir bien frío.",
    marcas: ["Fuente Clara", "Tropical Sur", "Burbuja", "Río Fresco"],
    presentaciones: [
      ["350 ml", 0.35],
      ["600 ml", 0.55],
      ["1 litro", 1],
      ["2 litros", 1.7],
      ["paquete de 6", 3.1],
    ],
    bases: [
      ["Agua sin gas", 95],
      ["Agua con gas", 115],
      ["Agua saborizada de limón", 140],
      ["Gaseosa de cola", 165],
      ["Gaseosa de naranja", 160],
      ["Gaseosa de limón", 160],
      ["Jugo de naranja", 240],
      ["Jugo de manzana", 245],
      ["Jugo de durazno", 250],
      ["Jugo de piña", 235],
      ["Néctar de mango", 255],
      ["Té helado de limón", 190],
      ["Té helado de durazno", 195],
      ["Bebida energizante", 420],
      ["Bebida isotónica", 280],
      ["Limonada", 185],
      ["Agua de coco", 330],
      ["Refresco de tamarindo", 175],
      ["Refresco de jamaica", 175],
      ["Horchata", 210],
      ["Café frío", 360],
      ["Malta", 230],
      ["Agua tónica", 220],
      ["Bebida de avena", 225],
      ["Kombucha", 480],
    ],
  },
  {
    nombre: "Snacks y dulces",
    color: "#C2477F",
    frase: "Ideal para compartir.",
    marcas: ["Crujimax", "Dulce Antojo", "Pica Pica", "La Golosina"],
    presentaciones: [
      ["40 g", 0.3],
      ["90 g", 0.6],
      ["180 g", 1],
      ["350 g", 1.8],
      ["paquete de 10", 2.7],
    ],
    bases: [
      ["Papas fritas clásicas", 240],
      ["Papas fritas con limón", 245],
      ["Papas fritas picantes", 250],
      ["Tortillas de maíz tostadas", 230],
      ["Palomitas con mantequilla", 210],
      ["Palomitas con caramelo", 260],
      ["Maní salado", 280],
      ["Maní japonés", 290],
      ["Mezcla de frutos secos", 620],
      ["Chicharrón", 310],
      ["Platanitos", 220],
      ["Yuquitas", 225],
      ["Galleta de chocolate", 270],
      ["Galleta rellena de vainilla", 255],
      ["Galleta salada", 215],
      ["Barra de cereal", 330],
      ["Chocolate con leche", 390],
      ["Chocolate amargo", 430],
      ["Chocolate blanco", 400],
      ["Caramelos de fruta", 180],
      ["Gomitas", 240],
      ["Chicle de menta", 150],
      ["Malvaviscos", 235],
      ["Paleta de caramelo", 160],
      ["Turrón de maní", 345],
    ],
  },
  {
    nombre: "Congelados",
    color: "#4A7FA5",
    frase: "Mantener congelado a -18 °C.",
    marcas: ["Polo Sur", "Frío Listo", "Nevada", "Cocina Exprés"],
    presentaciones: [
      ["250 g", 0.35],
      ["500 g", 0.6],
      ["1 kg", 1],
      ["1,5 kg", 1.45],
      ["caja de 2 kg", 1.85],
    ],
    bases: [
      ["Papas prefritas", 380],
      ["Vegetales mixtos", 340],
      ["Arvejas", 320],
      ["Maíz dulce", 310],
      ["Brócoli congelado", 360],
      ["Fresas congeladas", 620],
      ["Mora congelada", 640],
      ["Pulpa de maracuyá", 520],
      ["Pulpa de guanábana", 580],
      ["Nuggets de pollo", 760],
      ["Hamburguesas de res", 890],
      ["Hamburguesas de pollo", 820],
      ["Deditos de pescado", 840],
      ["Camarón precocido", 1650],
      ["Pizza de queso", 980],
      ["Pizza de pepperoni", 1050],
      ["Lasaña de carne", 1120],
      ["Empanadas de carne", 690],
      ["Tequeños", 720],
      ["Helado de vainilla", 650],
      ["Helado de chocolate", 660],
      ["Helado de fresa", 655],
      ["Paletas de agua", 430],
      ["Masa de hojaldre", 470],
      ["Yuca congelada", 290],
    ],
  },
  {
    nombre: "Limpieza del hogar",
    color: "#5E6BB8",
    frase: "Mantener fuera del alcance de los niños.",
    marcas: ["Brillo Total", "Casa Limpia", "Fresco Hogar", "Poder Azul"],
    presentaciones: [
      ["250 ml", 0.35],
      ["500 ml", 0.6],
      ["1 litro", 1],
      ["2 litros", 1.8],
      ["galón", 3.2],
    ],
    bases: [
      ["Detergente líquido", 520],
      ["Suavizante de ropa", 430],
      ["Cloro", 180],
      ["Desinfectante de pino", 290],
      ["Desinfectante de lavanda", 295],
      ["Limpiador multiusos", 340],
      ["Limpiavidrios", 310],
      ["Lavaplatos líquido de limón", 280],
      ["Lavaplatos líquido de manzana", 285],
      ["Desengrasante", 390],
      ["Limpiador de baños", 360],
      ["Limpiador de pisos", 330],
      ["Quitamanchas", 480],
      ["Cera para pisos", 520],
      ["Ambientador líquido", 350],
      ["Jabón líquido para ropa delicada", 560],
      ["Blanqueador sin cloro", 410],
      ["Limpiador de hornos", 470],
      ["Destapador de cañerías", 440],
      ["Abrillantador de muebles", 490],
      ["Limpiador de acero", 510],
      ["Antisarro", 380],
      ["Limpiador de alfombras", 540],
      ["Alcohol de limpieza", 260],
      ["Vinagre de limpieza", 170],
    ],
  },
  {
    nombre: "Cuidado personal",
    color: "#7B4FA3",
    frase: "Uso externo.",
    marcas: ["Piel Suave", "Aura", "Vital Care", "Brisa"],
    presentaciones: [
      ["tamaño viaje de 60 ml", 0.3],
      ["200 ml", 0.6],
      ["400 ml", 1],
      ["750 ml", 1.7],
      ["paquete de 2", 1.9],
    ],
    bases: [
      ["Champú clásico", 480],
      ["Champú anticaspa", 560],
      ["Acondicionador", 490],
      ["Jabón líquido de manos", 290],
      ["Gel de baño", 420],
      ["Crema corporal", 540],
      ["Crema de manos", 380],
      ["Protector solar", 980],
      ["Enjuague bucal", 450],
      ["Gel para el cabello", 330],
      ["Crema para peinar", 410],
      ["Desodorante en aerosol", 470],
      ["Espuma de afeitar", 440],
      ["Loción para después de afeitar", 620],
      ["Agua micelar", 690],
      ["Desmaquillante", 580],
      ["Tónico facial", 640],
      ["Jabón íntimo", 520],
      ["Aceite corporal", 710],
      ["Talco", 310],
      ["Alcohol en gel", 270],
      ["Tratamiento capilar", 760],
      ["Colonia fresca", 850],
      ["Exfoliante corporal", 730],
      ["Repelente de insectos", 560],
    ],
  },
  {
    nombre: "Bebés",
    color: "#D9822B",
    frase: "Probado por pediatras.",
    marcas: ["Nenitos", "Dulce Cuna", "Pequeñín", "Mimo"],
    presentaciones: [
      ["tamaño de prueba", 0.2],
      ["pequeño", 0.5],
      ["mediano", 1],
      ["grande", 1.7],
      ["paquete ahorro", 2.9],
    ],
    bases: [
      ["Pañales recién nacido", 1250],
      ["Pañales talla P", 1280],
      ["Pañales talla M", 1320],
      ["Pañales talla G", 1360],
      ["Pañales talla XG", 1400],
      ["Pañales de entrenamiento", 1480],
      ["Toallitas húmedas", 340],
      ["Toallitas húmedas sin aroma", 360],
      ["Champú para bebé", 520],
      ["Jabón para bebé", 280],
      ["Crema para rozaduras", 640],
      ["Aceite para bebé", 560],
      ["Talco para bebé", 390],
      ["Loción para bebé", 590],
      ["Colonia para bebé", 610],
      ["Fórmula infantil etapa 1", 2350],
      ["Fórmula infantil etapa 2", 2280],
      ["Fórmula infantil etapa 3", 2190],
      ["Cereal infantil de arroz", 480],
      ["Cereal infantil de avena", 490],
      ["Papilla de manzana", 210],
      ["Papilla de pera", 215],
      ["Papilla de verduras", 225],
      ["Galletas para bebé", 320],
      ["Detergente para ropa de bebé", 780],
    ],
  },
  {
    nombre: "Mascotas",
    color: "#55764A",
    frase: "Alimento y cuidado para tu mascota.",
    marcas: ["Patitas", "Fiel Amigo", "Bigotes", "Cola Feliz"],
    presentaciones: [
      ["500 g", 0.3],
      ["1 kg", 0.55],
      ["2 kg", 1],
      ["4 kg", 1.85],
      ["saco de 10 kg", 4.2],
    ],
    bases: [
      ["Alimento para perro adulto", 1150],
      ["Alimento para perro cachorro", 1280],
      ["Alimento para perro de raza pequeña", 1320],
      ["Alimento para perro de raza grande", 1190],
      ["Alimento para perro sénior", 1350],
      ["Alimento para gato adulto", 1240],
      ["Alimento para gato cachorro", 1380],
      ["Alimento para gato esterilizado", 1460],
      ["Alimento de pollo para perro", 1210],
      ["Alimento de res para perro", 1230],
      ["Alimento de salmón para gato", 1520],
      ["Alimento de atún para gato", 1490],
      ["Galletas para perro", 890],
      ["Premios para gato", 960],
      ["Huesos masticables", 1040],
      ["Arena para gato", 720],
      ["Arena aglomerante para gato", 940],
      ["Alimento para aves", 580],
      ["Alimento para peces", 1650],
      ["Alimento para conejo", 760],
      ["Alimento para hámster", 820],
      ["Viruta para jaulas", 490],
      ["Heno para roedores", 610],
      ["Alimento húmedo para perro", 1090],
      ["Alimento húmedo para gato", 1180],
    ],
  },
];
